org.gradle.jvmargs = -Xmx3G

# Project
maven_group = tech.thatgravyboat.winteroverhaul
mod_version = 5.0.0
mod_id = winteroverhaul
mod_name = WinterOverhaul

# Minecraft
minecraft_version = 1.21.8
parchment_version = 1.21.8
parchment_snapshot = 2025.07.20
supported_versions = 1.21.7,1.21.8

# Fabric
fabric_loader_version = 0.17.2
fabric_api_version = 0.133.4+1.21.8

# NeoForge
neoforge_version = 21.8.46
minecraft_version_forge = [1.21.8,1.21.9)

# Dependencies
geckolib_version = 5.2.2
# https://modrinth.com/mod/architectury-api/versions?g=1.21.8
architectury_version = 17.0.8

# Publishing
publishing.curseforge = 564989
publishing.modrinth = 5M97aUS6